import { test, expect } from '@playwright/test'
test('home, article search and 404 work', async ({page}) => {
  await page.goto('/'); await expect(page.locator('h1')).toBeVisible()
  await page.goto('/articles'); await page.getByPlaceholder('搜索文章标题或标签...').fill('CMake'); await expect(page.getByText('CMake学习笔记')).toBeVisible()
  await page.goto('/missing-page'); await expect(page.getByRole('heading', { name: '404' })).toBeVisible()
})
test('theme choice persists', async ({page}) => { await page.goto('/'); await page.getByRole('button',{name:/当前主题/}).click(); await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme',/light|dark/) })
test('light theme keeps code blocks readable', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('theme', 'light'))
  await page.goto('/articles/cmake-notes')
  const code = page.locator('.article-content pre code').first()
  await expect(code).toBeVisible()
  await expect(code).toHaveCSS('color', 'rgb(48, 53, 47)')
  await expect(page.locator('.article-content pre').first()).toHaveCSS('background-color', 'rgb(238, 233, 223)')
})
test('articles with a table of contents use vertical reading progress', async ({ page }) => {
  await page.goto('/articles/cmake-notes')
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  const progress = page.locator('.toc-nav')
  await expect(progress).toHaveCSS('--toc-progress', '0%')
  await page.locator('.article-content').evaluate(element => window.scrollTo(0, element.offsetTop + element.offsetHeight))
  await expect.poll(async () => Number((await progress.evaluate(element => getComputedStyle(element).getPropertyValue('--toc-progress'))).replace('%', ''))).toBeGreaterThan(95)
  await expect(page.locator('.toc-sidebar')).toHaveCSS('position', 'sticky')
})
test('article covers live on list cards, not detail headers', async ({ page }) => {
  await page.goto('/articles')
  await expect(page.locator('.article-card-media img').first()).toBeVisible()
  await page.locator('.article-card').first().click()
  await expect(page.locator('.article-header .header-cover')).toHaveCount(0)
})
test('VPS writing entry and route are restricted to administrators', async ({ page }) => {
  await page.route('**/api/v1/me', route => route.fulfill({ json: null }))
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'GitHub 登录' })).toBeVisible()
  await expect(page.getByRole('link', { name: '写作' })).toHaveCount(0)
  await page.goto('/write')
  await expect(page).toHaveURL('/')
})
test('writing studio keeps drafts when saving and creating articles', async ({ page }) => {
  test.setTimeout(60000)
  await page.route('**/api/v1/me', route => route.fulfill({ json: { id: '1', login: 'admin', avatarUrl: '', role: 'admin' } }))
  await page.goto('/write')
  await expect(page.locator('.draft-item.published')).toHaveCount(7)
  await page.getByRole('button', { name: '新建', exact: true }).click()
  await page.getByLabel('标题').fill('Vue 写作测试')
  await page.locator('.markdown-editor textarea').fill('## 第一节\n\n这是预览正文，~~仅删除这段~~，其余正常。')
  await expect(page.locator('.preview-article')).toContainText('Vue 写作测试')
  await expect(page.locator('.preview-article')).toContainText('这是预览正文')
  await expect(page.locator('.preview-article del')).toHaveText('仅删除这段')
  await page.locator('.image-picker input').setInputFiles('apps/web/public/image/4.png')
  await page.locator('.image-insert').click()
  await expect(page.locator('.markdown-editor textarea')).toHaveValue(/\/image\/4\.png/)
  page.once('dialog', dialog => dialog.accept('renamed.png'))
  await page.getByRole('button', { name: '重命名图片：4.png' }).click()
  await expect(page.locator('.markdown-editor textarea')).toHaveValue(/\/image\/renamed\.png/)
  await page.getByRole('button', { name: '删除图片：renamed.png' }).click()
  await expect(page.locator('.markdown-editor textarea')).not.toHaveValue(/\/image\/renamed\.png/)
  await page.locator('.cover-drop input').setInputFiles('apps/web/public/image/5.png')
  page.once('dialog', dialog => dialog.accept('cover-renamed.png'))
  await page.getByRole('button', { name: '重命名', exact: true }).click()
  await expect(page.locator('.cover-file')).toContainText('cover-renamed.png')
  await page.getByRole('button', { name: '新建', exact: true }).click()
  await expect(page.locator('.draft-item').filter({ hasText: 'Vue 写作测试' })).toBeVisible()
  await expect(page.getByLabel('标题')).toHaveValue('')
  await page.getByLabel('标题').fill('第二篇草稿')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('.draft-item').filter({ hasText: '第二篇草稿' })).toBeVisible()
  await expect(page.getByText('已保存', { exact: true })).toBeVisible()
  await page.goto('/articles')
  await expect(page.getByText('第二篇草稿', { exact: true })).toHaveCount(0)
  await page.goto('/write')
  await page.locator('.draft-item').filter({ hasText: '第二篇草稿' }).getByRole('button').first().click()
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await page.goto('/articles')
  await expect(page.getByText('第二篇草稿', { exact: true })).toBeVisible()
  await page.goto('/write')
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.draft-item').filter({ hasText: 'Vue 写作测试' }).getByRole('button', { name: /删除文章/ }).click()
  await page.getByRole('button', { name: /垃圾箱/ }).click()
  const trashed = page.locator('.trash-item').filter({ hasText: 'Vue 写作测试' })
  await expect(trashed).toBeVisible()
  await trashed.getByRole('button', { name: '恢复' }).click()
  await expect(page.locator('.draft-item').filter({ hasText: 'Vue 写作测试' })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('.draft-item').filter({ hasText: 'Vue 写作测试' }).getByRole('button', { name: /删除文章/ }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '清空垃圾箱' }).click()
  await expect(page.locator('.trash-box')).toHaveCount(0)
})
